app/home/__init__.py
# -*- coding: utf-8 -*-
"""The home module."""
from . import views  # noqa

app/home/views.py
# -*- coding: utf-8 -*-
"""Home views."""
from flask import request, Blueprint, render_template, redirect, session, url_for
from flask_login import login_user
from saml2 import entity
from ..saml.config import metadata_url_for
from ..saml.client import saml_client_for
from ..user import user_store, User

blueprint = Blueprint('home', __name__, template_folder='templates')


@blueprint.route('/')
def main_page():
    return render_template('main_page.html', idp_dict=metadata_url_for)


@blueprint.route("/saml/login/<idp_name>")
def sp_initiated(idp_name):
    saml_client = saml_client_for(idp_name)
    reqid, info = saml_client.prepare_for_authenticate()

    redirect_url = None
    for key, value in info['headers']:
        if key is 'Location':
            redirect_url = value
    response = redirect(redirect_url, code=302)

    response.headers['Cache-Control'] = 'no-cache, no-store'
    response.headers['Pragma'] = 'no-cache'
    return response


@blueprint.route("/saml/sso/<idp_name>", methods=['POST'])
def idp_initiated(idp_name):
    saml_client = saml_client_for(idp_name)
    authn_response = saml_client.parse_authn_request_response(
        request.form['SAMLResponse'],
        entity.BINDING_HTTP_POST)
    authn_response.get_identity()
    user_info = authn_response.get_subject()
    username = user_info.text

    if username not in user_store:
        user_store[username] = {
            'first_name': authn_response.ava['firstName'][0],
            'last_name': authn_response.ava['lastName'][0],
        }
    user = User(username)
    session['saml_attributes'] = authn_response.ava
    login_user(user)
    # url = url_for('user')
    if 'RelayState' in request.form:
        url = request.form['RelayState']
    return redirect(url)

app/home/templates/base.html
{% extends "bootstrap/base.html" %}
{% set application_name = 'Flask use OKTA SAML2.0' %}
{% block title %}{{ application_name }}{% endblock %}
{% block body_attribs %} style="padding-top: 60px"{% endblock %}
{% block navbar %}
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{{ url_for('home.main_page') }}">{{ application_name }}</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
	    {% if current_user.is_authenticated %}
            <li><a href="{{ url_for('user.logout') }}">Logout</a></li>
	    {% endif %}
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
  <div class="container">
  {% endblock %}
  {% block content %}
  </div>
{% endblock %}

app/home/templates/main_page.html
{% extends 'base.html' %}
{% block content %}
{% if current_user.is_authenticated %}
<div class="container">
  <h1>Logged in</h1>
  <p class="lead">
    Contents of the most recent SAML assertion:
    </p>
  <div class="col-md-8">
    <table class="table">
    {% if session.saml_attributes %}
      {% for attribute in session.saml_attributes.keys() %}
      <tr>
	<td>{{ attribute }}</td>
	<td>{{ session.saml_attributes[attribute][0] }}</td>
      </tr>
      {% endfor %}
    {% endif %}
    </table>
  </div>
</div>
{% else %}
<p class="lead">Select the IdP you want to use to authenticate:</p>
<ol>
  {% for idp in idp_dict.keys() %}
  <li><a href="/saml/login/{{idp}}">{{idp}}</a></li>
  {% endfor %}
</ol>
{% endif %}
{% endblock %}

app/home/templates/unauthorized.html
{% extends 'base.html' %}
{% block content %}
<h1>Unauthorized</h1>
<p>
  The server could not verify that you are authorized to access the URL requested. You either supplied the wrong credentials (e.g. a bad password), or your browser doesn't understand how to supply the credentials required.
</p>
{% endblock %}